## Kubernetes Deployment Configuration YAML
# Zep Server
# Note: This is designed for development/test deployments
# Will need to be customized and hardened with additional security, deployment configurations for production use cases
##
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zep-postgres
  namespace: zep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zep-postgres
  template:
    metadata:
      labels:
        app: zep-postgres
    spec:
      containers:
        - name: zep-postgres
          image: ghcr.io/getzep/postgres:latest
          ports:
            - name: postgres-port
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -q
                - -d
                - postgres
                - -U
                - postgres
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zep-nlp
  namespace: zep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zep-nlp
  template:
    metadata:
      labels:
        app: zep-nlp
    spec:
      containers:
        - name: zep-nlp
          image: ghcr.io/getzep/zep-nlp-server:latest
          readinessProbe:
            httpGet:
              port: 5557
              path: /healthz
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
          ports:
            - containerPort: 5557
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zep
  namespace: zep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zep
  template:
    metadata:
      labels:
        app: zep
    spec:
      containers:
        - name: zep
          image: ghcr.io/getzep/zep-cloud:latest
          ports:
            - containerPort: 8000
          envFrom:
          # To create a config map from your local config.yaml file, run:
          # kubectl create configmap zep-config --from-file=config.yaml -n zep
            - configMapRef:
                name: zep-config
          # To create a config map from your local .env file, run:
          # kubectl create configmap dotenv --from-file=.env -n zep
            - configMapRef:
                name: dotenv
           Uncomment to enable pulling config from the configmap
           env:
           env:
             - name: ZEP_STORE_POSTGRES_DSN
               value: postgres://postgres:postgres@zep-postgres:5432/postgres?sslmode=disable
             - name: ZEP_NLP_SERVER_URL
               value: http://zep-nlp:5557
             - name: ZEP_OPENAI_API_KEY
               valueFrom:
                 secretKeyRef:
                   name: zep-openai-api-key
                   key: ZEP_OPENAI_API_KEY
             - name: AZURE_OPENAI_SUBSCRIPTION_KEY
               valueFrom:
                 secretKeyRef:
                   name: azure-openai-secret
                   key: subscription-key
             - name: AZURE_OPENAI_ENDPOINT
               valueFrom:
                 secretKeyRef:
                   name: azure-openai-secret
                   key: endpoint
              value: postgres://postgres:postgres@zep-postgres:5432/postgres?sslmode=disable
             - name: ZEP_NLP_SERVER_URL
               value: http://zep-nlp:5557
             - name: ZEP_OPENAI_API_KEY
               valueFrom:
                 secretKeyRef:
                   name: zep-openai-api-key
                 key: ZEP_OPENAI_API_KEY
            - name: AZURE_OPENAI_SUBSCRIPTION_KEY
              valueFrom:
                 secretKeyRef:
                  name: azure-openai-secret
                   key: subscription-key
            - name: AZURE_OPENAI_ENDPOINT
              valueFrom:
                secretKeyRef:
                   name: azure-openai-secret
                   key: endpoint
          readinessProbe:
            httpGet:
              port: 8000
              path: /healthz
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: zep-postgres
  namespace: zep
spec:
  selector:
    app: zep-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: zep-nlp
  namespace: zep
spec:
  selector:
    app: zep-nlp
  ports:
    - protocol: TCP
      port: 5557
      targetPort: 5557
---
apiVersion: v1
kind: Service
metadata:
  name: zep
  namespace: zep
spec:
  type: LoadBalancer
  selector:
    app: zep
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
