name: 'Test Integration Package'
description: 'Run linting, type checking, and tests for a Zep integration package'

inputs:
  package:
    description: 'Package name (e.g., autogen, crewai)'
    required: true
  python-version:
    description: 'Python version to test with'
    required: true
    default: '3.11'

runs:
  using: 'composite'
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python ${{ inputs.python-version }}
      shell: bash
      run: uv python install ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      working-directory: integrations/python/zep_${{ inputs.package }}
      run: uv sync --extra dev

    - name: Run linting
      shell: bash
      working-directory: integrations/python/zep_${{ inputs.package }}
      run: |
        uv run ruff check .
        uv run ruff format --check .

    - name: Run type checking
      shell: bash
      working-directory: integrations/python/zep_${{ inputs.package }}
      run: uv run mypy src/

    - name: Run tests
      shell: bash
      working-directory: integrations/python/zep_${{ inputs.package }}
      run: uv run pytest tests/ -v --cov=zep_${{ inputs.package }} --cov-report=xml

    - name: Upload coverage
      if: inputs.python-version == '3.11'
      uses: codecov/codecov-action@v4
      with:
        file: integrations/python/zep_${{ inputs.package }}/coverage.xml
        flags: ${{ inputs.package }}
        name: ${{ inputs.package }}-coverage