[project]
name = "openai-agents-sdk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "click>=8.1.8",
    "openai-agents>=0.0.3",
    "packaging>=24.2",
    "python-dotenv>=1.0.1",
    "zep-cloud>=2.6.1",
]
